spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    port: 6379
    host: 127.0.0.1

logging:
  level:
    org.hibernate.SQL: debug

rank:
  service:
    url: http://localhost:8080/rank/keyword